#!/usr/bin/env python3
"""WCAG 2.1 contrast-ratio verifier for the AugerLink palette.

Runs the 10 foreground/background pairs from `palette.md` through the
WCAG 2.1 relative-luminance formula, reports computed ratio + AA/AAA
pass/fail per the use-case threshold (3:1 or 4.5:1).

Usage:
    python3 design/wcag_verify.py            # human-readable table
    python3 design/wcag_verify.py --json     # machine-readable

The 10 pairs are the load-bearing color combinations the palette commits to.
If any combo fails AA, the palette doc says: bump the foreground value (V in
HSV) slightly toward the brighter end — keep the hue and the warm character.

WCAG 2.1 contrast formula:
    L = 0.2126*R + 0.7152*G + 0.0722*B   (each component sRGB-linearized)
    ratio = (L_lighter + 0.05) / (L_darker + 0.05)

References:
- https://www.w3.org/TR/WCAG21/#contrast-minimum
- https://www.w3.org/WAI/GL/wiki/Relative_luminance
"""

from __future__ import annotations
import argparse
import json
import sys
from dataclasses import dataclass


def _linearize(c8: int) -> float:
    """sRGB → linear RGB component, 8-bit input."""
    s = c8 / 255.0
    return s / 12.92 if s <= 0.03928 else ((s + 0.055) / 1.055) ** 2.4


def relative_luminance(hex_color: str) -> float:
    """Compute WCAG 2.1 relative luminance for a #RRGGBB hex string."""
    h = hex_color.lstrip("#")
    if len(h) != 6:
        raise ValueError(f"expected 6-digit hex, got {hex_color!r}")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _linearize(r) + 0.7152 * _linearize(g) + 0.0722 * _linearize(b)


def contrast_ratio(fg: str, bg: str) -> float:
    """WCAG 2.1 contrast ratio between two #RRGGBB colors."""
    l1 = relative_luminance(fg)
    l2 = relative_luminance(bg)
    lighter, darker = (l1, l2) if l1 >= l2 else (l2, l1)
    return (lighter + 0.05) / (darker + 0.05)


@dataclass(frozen=True)
class Pair:
    fg_token: str
    fg_hex: str
    bg_token: str
    bg_hex: str
    min_ratio: float          # 3.0 (large/UI) or 4.5 (body text)
    use_case: str


PAIRS: list[Pair] = [
    Pair("cream",        "#F5E6D3", "barn-dark",   "#1A1410", 4.5, "Body text on app bg"),
    Pair("cream",        "#F5E6D3", "charcoal",    "#0F0E0C", 4.5, "Text on cards/bubbles"),
    Pair("cream-muted",  "#C8B8A0", "barn-dark",   "#1A1410", 4.5, "Secondary text on app bg"),
    Pair("dusk-amber",   "#9C5519", "barn-dark",   "#1A1410", 3.0, "Primary button bg vs app bg"),
    Pair("cream",        "#F5E6D3", "dusk-amber",  "#9C5519", 4.5, "Button label on primary"),
    Pair("glow-orange",  "#D97826", "barn-dark",   "#1A1410", 3.0, "Outgoing bubble vs app bg"),
    Pair("barn-dark",    "#1A1410", "glow-orange", "#D97826", 4.5, "Outgoing bubble text"),
    Pair("gold",         "#FFC065", "barn-dark",   "#1A1410", 3.0, "Active indicator on app bg"),
    Pair("error",        "#E53E2C", "barn-dark",   "#1A1410", 3.0, "Error text/icon on app bg"),
    Pair("success",      "#7FA756", "barn-dark",   "#1A1410", 3.0, "Success text/icon on app bg"),
]


# WCAG AAA thresholds: 7:1 normal, 4.5:1 large/UI
def aaa_min(min_aa: float) -> float:
    return 7.0 if min_aa == 4.5 else 4.5


def evaluate(pair: Pair) -> dict:
    ratio = contrast_ratio(pair.fg_hex, pair.bg_hex)
    aa = ratio >= pair.min_ratio
    aaa = ratio >= aaa_min(pair.min_ratio)
    return {
        "fg_token": pair.fg_token,
        "fg_hex": pair.fg_hex,
        "bg_token": pair.bg_token,
        "bg_hex": pair.bg_hex,
        "ratio": round(ratio, 2),
        "min_aa": pair.min_ratio,
        "min_aaa": aaa_min(pair.min_ratio),
        "passes_aa": aa,
        "passes_aaa": aaa,
        "use_case": pair.use_case,
    }


def render_table(results: list[dict]) -> str:
    rows = [
        "| Foreground | Background | Ratio | AA | AAA | Use Case |",
        "|---|---|---|---|---|---|",
    ]
    for r in results:
        aa = "✅" if r["passes_aa"] else "❌"
        aaa = "✅" if r["passes_aaa"] else "—"
        rows.append(
            f"| `{r['fg_token']}` `{r['fg_hex']}` "
            f"| `{r['bg_token']}` `{r['bg_hex']}` "
            f"| **{r['ratio']:.2f}:1** (need {r['min_aa']:.0f}:1) "
            f"| {aa} | {aaa} | {r['use_case']} |"
        )
    return "\n".join(rows)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--json", action="store_true", help="emit JSON instead of markdown table")
    p.add_argument("--strict", action="store_true", help="exit 1 if any pair fails AA")
    args = p.parse_args(argv)

    results = [evaluate(pair) for pair in PAIRS]
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        print("# AugerLink Palette — WCAG 2.1 Contrast Verification\n")
        print(f"Generated by `design/wcag_verify.py` (deterministic).\n")
        print(render_table(results))
        print()
        n_fail = sum(1 for r in results if not r["passes_aa"])
        n_aaa = sum(1 for r in results if r["passes_aaa"])
        print(f"\n**Summary**: {len(results) - n_fail}/{len(results)} pairs pass AA; "
              f"{n_aaa}/{len(results)} pairs also pass AAA.")
        if n_fail:
            print(f"\n⚠️  {n_fail} pair(s) FAIL AA — adjust foreground value (HSV V) toward brighter end "
                  "while keeping hue + warm character per palette.md guidance.")

    if args.strict and any(not r["passes_aa"] for r in results):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
